package Segona_part_ABP;
// Generated May 11, 2026, 11:52:23 AM by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Partides generated by hbm2java
 */
public class Partides implements java.io.Serializable {

	private Integer idPlayer;
	private String name;
	private Integer score;
	private Timestamp date;
	private String language;

	public Partides() {
	}

	public Partides(String name, Integer score, Timestamp date, String language) {
		this.name = name;
		this.score = score;
		this.date = date;
		this.language = language;
	}

	public Integer getIdPlayer() {
		return this.idPlayer;
	}

	public void setIdPlayer(Integer idPlayer) {
		this.idPlayer = idPlayer;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Timestamp getDate() {
		return this.date;
	}

	public void setDate(Timestamp date) {
		this.date = date;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

}
